package com.dryzaite.carquiz.shared.model

import com.dryzaite.carquiz.shared.R

object BrandCatalog {
    val allBrands: List<CarBrand> = listOf(
        CarBrand("audi", "Audi", BrandRegion.EU, R.drawable.ic_audi, 0xFFB0BEC5),
        CarBrand("bmw", "BMW", BrandRegion.EU, R.drawable.ic_bmw, 0xFF1565C0),
        CarBrand("mercedes", "Mercedes-Benz", BrandRegion.EU, R.drawable.ic_mercedes, 0xFF546E7A),
        CarBrand("volkswagen", "Volkswagen", BrandRegion.EU, R.drawable.ic_volkswagen, 0xFF0D47A1),
        CarBrand("porsche", "Porsche", BrandRegion.EU, R.drawable.ic_porsche, 0xFF6D4C41),
        CarBrand("volvo", "Volvo", BrandRegion.EU, R.drawable.ic_volvo, 0xFF607D8B),
        CarBrand("renault", "Renault", BrandRegion.EU, R.drawable.ic_renault, 0xFFF9A825),
        CarBrand("peugeot", "Peugeot", BrandRegion.EU, R.drawable.ic_peugeot, 0xFF37474F),
        CarBrand("ferrari", "Ferrari", BrandRegion.EU, R.drawable.ic_ferrari, 0xFFC62828),
        CarBrand("lamborghini", "Lamborghini", BrandRegion.EU, R.drawable.ic_lamborghini, 0xFFF9A825),
        CarBrand("fiat", "Fiat", BrandRegion.EU, R.drawable.ic_fiat, 0xFF1565C0),
        CarBrand("citroen", "Citroën", BrandRegion.EU, R.drawable.ic_citroen, 0xFFE53935),
        CarBrand("skoda", "Škoda", BrandRegion.EU, R.drawable.ic_skoda, 0xFF2E7D32),
        CarBrand("seat", "SEAT", BrandRegion.EU, R.drawable.ic_seat, 0xFF37474F),
        CarBrand("opel", "Opel", BrandRegion.EU, R.drawable.ic_opel, 0xFF455A64),
        CarBrand("mini_cooper", "Mini Cooper", BrandRegion.EU, R.drawable.ic_mini, 0xFF616161),
        CarBrand("bugatti", "Bugatti", BrandRegion.EU, R.drawable.ic_bugatti, 0xFF0D47A1),
        CarBrand("bentley", "Bentley", BrandRegion.EU, R.drawable.ic_bentley, 0xFF2E7D32),
        CarBrand("maserati", "Maserati", BrandRegion.EU, R.drawable.ic_maserati, 0xFF1565C0),
        CarBrand("mclaren", "McLaren", BrandRegion.EU, R.drawable.ic_mclaren, 0xFFFF6F00),
        CarBrand("astonmartin", "Aston Martin", BrandRegion.EU, R.drawable.ic_astonmartin, 0xFF004D40),
        CarBrand("rollsroyce", "Rolls-Royce", BrandRegion.EU, R.drawable.ic_rollsroyce, 0xFF263238),
        CarBrand("ford", "Ford", BrandRegion.USA, R.drawable.ic_ford, 0xFF0D47A1),
        CarBrand("chevrolet", "Chevrolet", BrandRegion.USA, R.drawable.ic_chevrolet, 0xFFFBC02D),
        CarBrand("tesla", "Tesla", BrandRegion.USA, R.drawable.ic_tesla, 0xFFD32F2F),
        CarBrand("jeep", "Jeep", BrandRegion.USA, R.drawable.ic_jeep, 0xFF33691E),
        CarBrand("cadillac", "Cadillac", BrandRegion.USA, R.drawable.ic_cadillac, 0xFF455A64),
        CarBrand("gmc", "GMC", BrandRegion.USA, R.drawable.ic_gmc, 0xFFC62828),
        CarBrand("lincoln", "Lincoln", BrandRegion.USA, R.drawable.ic_lincoln, 0xFF37474F),
        CarBrand("chrysler", "Chrysler", BrandRegion.USA, R.drawable.ic_chrysler, 0xFF546E7A),
        CarBrand("ram", "Ram", BrandRegion.USA, R.drawable.ic_ram, 0xFF37474F),
        CarBrand("toyota", "Toyota", BrandRegion.JAPAN, R.drawable.ic_toyota, 0xFFD32F2F),
        CarBrand("honda", "Honda", BrandRegion.JAPAN, R.drawable.ic_honda, 0xFFB71C1C),
        CarBrand("nissan", "Nissan", BrandRegion.JAPAN, R.drawable.ic_nissan, 0xFF455A64),
        CarBrand("mazda", "Mazda", BrandRegion.JAPAN, R.drawable.ic_mazda, 0xFF283593),
        CarBrand("subaru", "Subaru", BrandRegion.JAPAN, R.drawable.ic_subaru, 0xFF1E88E5),
        CarBrand("infiniti", "Infiniti", BrandRegion.JAPAN, R.drawable.ic_infiniti, 0xFF546E7A),
        CarBrand("mitsubishi", "Mitsubishi", BrandRegion.JAPAN, R.drawable.ic_mitsubishi, 0xFFD32F2F),
        CarBrand("suzuki", "Suzuki", BrandRegion.JAPAN, R.drawable.ic_suzuki, 0xFF1976D2),
        CarBrand("acura", "Acura", BrandRegion.JAPAN, R.drawable.ic_acura, 0xFF455A64),
    )
}
