package com.dryzaite.carquiz.shared.model

object BrandCatalog {
    val allBrands: List<CarBrand> = listOf(
        CarBrand("audi", "Audi", BrandRegion.EU, "AU", 0xFFB0BEC5),
        CarBrand("bmw", "BMW", BrandRegion.EU, "BM", 0xFF1565C0),
        CarBrand("mercedes", "Mercedes-Benz", BrandRegion.EU, "MB", 0xFF546E7A),
        CarBrand("volkswagen", "Volkswagen", BrandRegion.EU, "VW", 0xFF0D47A1),
        CarBrand("porsche", "Porsche", BrandRegion.EU, "PO", 0xFF6D4C41),
        CarBrand("volvo", "Volvo", BrandRegion.EU, "VO", 0xFF607D8B),
        CarBrand("renault", "Renault", BrandRegion.EU, "RE", 0xFFF9A825),
        CarBrand("peugeot", "Peugeot", BrandRegion.EU, "PE", 0xFF37474F),
        CarBrand("ferrari", "Ferrari", BrandRegion.EU, "FE", 0xFFC62828),
        CarBrand("lamborghini", "Lamborghini", BrandRegion.EU, "LA", 0xFFF9A825),
        CarBrand("fiat", "Fiat", BrandRegion.EU, "FI", 0xFF1565C0),
        CarBrand("citroen", "Citroën", BrandRegion.EU, "CI", 0xFFE53935),
        CarBrand("skoda", "Škoda", BrandRegion.EU, "SK", 0xFF2E7D32),
        CarBrand("seat", "SEAT", BrandRegion.EU, "SE", 0xFF37474F),
        CarBrand("opel", "Opel", BrandRegion.EU, "OP", 0xFF455A64),
        CarBrand("mini", "MINI", BrandRegion.EU, "MI", 0xFF616161),
        CarBrand("bugatti", "Bugatti", BrandRegion.EU, "BU", 0xFF0D47A1),
        CarBrand("bentley", "Bentley", BrandRegion.EU, "BE", 0xFF2E7D32),
        CarBrand("maserati", "Maserati", BrandRegion.EU, "MS", 0xFF1565C0),
        CarBrand("mclaren", "McLaren", BrandRegion.EU, "MC", 0xFFFF6F00),
        CarBrand("astonmartin", "Aston Martin", BrandRegion.EU, "AM", 0xFF004D40),
        CarBrand("rollsroyce", "Rolls-Royce", BrandRegion.EU, "RR", 0xFF263238),
        CarBrand("ford", "Ford", BrandRegion.USA, "FO", 0xFF0D47A1),
        CarBrand("chevrolet", "Chevrolet", BrandRegion.USA, "CH", 0xFFFBC02D),
        CarBrand("tesla", "Tesla", BrandRegion.USA, "TE", 0xFFD32F2F),
        CarBrand("jeep", "Jeep", BrandRegion.USA, "JE", 0xFF33691E),
        CarBrand("cadillac", "Cadillac", BrandRegion.USA, "CA", 0xFF455A64),
        CarBrand("gmc", "GMC", BrandRegion.USA, "GM", 0xFFC62828),
        CarBrand("lincoln", "Lincoln", BrandRegion.USA, "LI", 0xFF37474F),
        CarBrand("chrysler", "Chrysler", BrandRegion.USA, "CR", 0xFF546E7A),
        CarBrand("ram", "Ram", BrandRegion.USA, "RA", 0xFF37474F),
        CarBrand("toyota", "Toyota", BrandRegion.JAPAN, "TO", 0xFFD32F2F),
        CarBrand("honda", "Honda", BrandRegion.JAPAN, "HO", 0xFFB71C1C),
        CarBrand("nissan", "Nissan", BrandRegion.JAPAN, "NI", 0xFF455A64),
        CarBrand("mazda", "Mazda", BrandRegion.JAPAN, "MA", 0xFF283593),
        CarBrand("subaru", "Subaru", BrandRegion.JAPAN, "SU", 0xFF1E88E5),
        CarBrand("infiniti", "Infiniti", BrandRegion.JAPAN, "IN", 0xFF546E7A),
        CarBrand("mitsubishi", "Mitsubishi", BrandRegion.JAPAN, "MT", 0xFFD32F2F),
        CarBrand("suzuki", "Suzuki", BrandRegion.JAPAN, "SZ", 0xFF1976D2),
        CarBrand("acura", "Acura", BrandRegion.JAPAN, "AC", 0xFF455A64),
    )
}
